apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksdemo-live1
  region: us-west-2
iam:
  withOIDC: true
vpc:
  subnets:
    public:
      us-east-1a: { id: subnet-0a6d9204c9ed93dc4 }
      us-east-1b: { id: subnet-08ed0df573ccb4b1d }
      us-east-1c: { id: subnet-0075bf41175a2cbb1 }
managedNodeGroups:
  - name: eksdemo-live1
    amiFamily: AmazonLinux2
    subnets:
      - subnet-0a6d9204c9ed93dc4
      - subnet-08ed0df573ccb4b1d
      - subnet-0075bf41175a2cbb1
    instanceType: t2.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    volumeSize: 20
    propagateASGTags: true
    ssh:
      allow: true
      publicKeyName: kube
    iam:
      withAddonPolicies:
        externalDNS: true
        imageBuilder: true
        appMesh: true
        albIngress: true


# for more details
 # https://eksctl.io/usage/schema/
 # https://eksctl.io/usage/creating-and-managing-clusters/
 # https://eksctl.io/usage/dry-run/
