apiVersion: v1
kind: Pod
metadata:
  name: myapp5
  labels:
    app: myapp5
spec:
  containers:
    - name: nodeapp
      image: sstechnosolutions/myapp:v0
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
